apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- frontend
- backend

images:
- name: psuhalka/todo-app-frontend
  newTag: latest
- name: psuhalka/todo-app-backend
  newTag: latest
