apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: todo-app
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - environment: dev
        url: https://kubernetes.default.svc
        namespace: todo-dev
      - environment: staging
        url: https://kubernetes.default.svc
        namespace: todo-staging
      - environment: prod
        url: https://kubernetes.default.svc
        namespace: todo-prod
  template:
    metadata:
      name: todo-{{environment}}
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/psuhalka/todo-app-gitops.git
        targetRevision: main
        path: gitops/apps/overlays/{{environment}}
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
