apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-dev

bases:
- ../../base/frontend
- ../../base/backend

commonLabels:
  env: dev

images:
- name: psuhalka/todo-app-frontend
  newTag: latest
- name: psuhalka/todo-app-backend
  newTag: latest

resources:
- namespace.yaml
- secret.yaml
